import { useState } from "react";
import { MovieCard } from "./MovieCard";
import { Category } from "./Category";
import { HeroComponent } from "./HeroComponent";

const fetched = false;

export default function App() {
  const [trending, setTrending] = useState(initialTrending);
  // if (!fetched) fetchData(setTrending);
  return (
    <>
      <HeroComponent heroMovie={initialTrending[3]} />
      <Category categoryName={"Trending"} categoryTitles={trending} />
      <Category categoryName={"Trending"} categoryTitles={trending} />
    </>
  );
}

const initialTrending = [
  {
    backdrop_path: "/2fxnTXr8NwyTFkunkimJkGkhqfy.jpg",
    id: 1118031,
    title: "Apocalypse Z: The Beginning of the End",
    original_title: "Apocalipsis Z: El principio del fin",
    overview:
      "A rabies-like disease spreads across the planet, transforming people into aggressive creatures. Manel takes refuge at home with his cat, using his wits to survive. Soon, they’ll have to leave for food, looking for safe places on land and sea. A story of survival, both physical and emotional, with action, tension, a rabid infection... and a grumpy cat.",
    poster_path: "/hSmOrZl8ON2aJk6xvjNgVQiPdCP.jpg",
    media_type: "movie",
    adult: false,
    original_language: "es",
    genre_ids: [28, 14, 27],
    popularity: 133.75,
    release_date: "2024-10-04",
    video: false,
    vote_average: 6.1,
    vote_count: 23,
  },
  {
    backdrop_path: "/7h6TqPB3ESmjuVbxCxAeB1c9OB1.jpg",
    id: 933260,
    title: "The Substance",
    original_title: "The Substance",
    overview:
      "A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.",
    poster_path: "/lqoMzCcZYEFK729d6qzt349fB4o.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [18, 27, 53],
    popularity: 2333.204,
    release_date: "2024-09-07",
    video: false,
    vote_average: 7.302,
    vote_count: 1099,
  },
  {
    backdrop_path: "/mNmfm7plMau7njFZcW63kbJM0S9.jpg",
    id: 1142518,
    title: "Freedom",
    original_title: "Libre",
    overview:
      "Inspired by the true events of one of France’s most notorious non-violent robbers, Bruno Sulak, in the 1980s. He led multiple heists, then captured public attention for his many daring escapes from police custody…always to reunite with his beloved lover and accomplice Annie, becoming both France’s Public Enemy #1 and an icon of Freedom.",
    poster_path: "/b2YL2kncIqlcDcqly78AsOPJi6r.jpg",
    media_type: "movie",
    adult: false,
    original_language: "fr",
    genre_ids: [28, 10749, 18],
    popularity: 11.622,
    release_date: "2024-11-01",
    video: false,
    vote_average: 6.5,
    vote_count: 2,
  },
  {
    backdrop_path: "/tEYp1Z1XhuFmqK0WAMh5DYz9SUT.jpg",
    id: 889737,
    title: "Joker: Folie à Deux",
    original_title: "Joker: Folie à Deux",
    overview:
      "While struggling with his dual identity, Arthur Fleck not only stumbles upon true love, but also finds the music that's always been inside him.",
    poster_path: "/aciP8Km0waTLXEYf5ybFK5CSUxl.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [18, 80, 53],
    popularity: 2117.657,
    release_date: "2024-10-01",
    video: false,
    vote_average: 5.736,
    vote_count: 1163,
  },
  {
    backdrop_path: "/qYvOcinXcnebhmCxYeivurh91T1.jpg",
    id: 827931,
    title: "Time Cut",
    original_title: "Time Cut",
    overview:
      "A teen in 2024 accidentally time-travels to 2003, days before a masked killer murders her sister. Can she change the past without destroying the future?",
    poster_path: "/gzMFMmpJHOmOFKsAhSDac62Dyg2.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [27, 878, 53],
    popularity: 121.078,
    release_date: "2024-10-29",
    video: false,
    vote_average: 5.7,
    vote_count: 52,
  },
  {
    backdrop_path: "/tYLXJW1sZQU09VWY1BhSVPKGIwc.jpg",
    id: 138501,
    name: "Agatha All Along",
    original_name: "Agatha All Along",
    overview:
      "Agatha Harkness gathers a coven of witches and sets off down, down, down The Witches' Road.",
    poster_path: "/1tfCj5h0FEQ5xg8hzVjQgcuGlgN.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [10765, 9648],
    popularity: 1492.666,
    first_air_date: "2024-09-18",
    vote_average: 7.793,
    vote_count: 403,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/XqKRa7Dp1kYiZADTz31PfyD6qD.jpg",
    id: 1182047,
    title: "The Apprentice",
    original_title: "The Apprentice",
    overview:
      "A young Donald Trump, eager to make his name as a hungry scion of a wealthy family in 1970s New York, comes under the spell of Roy Cohn, the cutthroat attorney who would help create the Donald Trump we know today. Cohn sees in Trump the perfect protégé—someone with raw ambition, a hunger for success, and a willingness to do whatever it takes to win.",
    poster_path: "/5icMlNq4rx6XJ9luWAR1Nr3M9rZ.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [18, 36],
    popularity: 41.241,
    release_date: "2024-10-09",
    video: false,
    vote_average: 7.1,
    vote_count: 101,
  },
  {
    backdrop_path: "/xMM0RE6WjfmZKtffj2JReMjNhDC.jpg",
    id: 1012201,
    title: "HAIKYU!! The Dumpster Battle",
    original_title: "劇場版ハイキュー!! ゴミ捨て場の決戦",
    overview:
      "Shoyo Hinata joins Karasuno High's volleyball club to be like his idol, a former Karasuno player known as the 'Little Giant'. But Hinata soon learns that he must team up with his middle school nemesis, Tobio Kageyama. Their clashing styles form a surprising weapon, but can their newfound teamwork defeat their rival Nekoma High in the highly anticipated 'Dumpster Battle', the long awaited ultimate showdown between two opposing underdog teams?",
    poster_path: "/ntRU0OA4etGGiMMmH1Yw0bnaMdW.jpg",
    media_type: "movie",
    adult: false,
    original_language: "ja",
    genre_ids: [16, 18],
    popularity: 185.548,
    release_date: "2024-02-16",
    video: false,
    vote_average: 7,
    vote_count: 101,
  },
  {
    backdrop_path: "/nTaITR6X8RkXrG32y67IIL4Oi5k.jpg",
    id: 1361292,
    title: "Cellar Door",
    original_title: "Cellar Door",
    overview:
      "Looking for a fresh start after a miscarriage, a couple find themselves being gifted the house of their dreams with one caveat - they can never open the cellar door. Whether they can live without knowing triggers shocking consequences.",
    poster_path: "/rB90k4l1L6G5Ub6Fuhb7viyu6Pj.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [27, 53],
    popularity: 34.497,
    release_date: "2024-10-31",
    video: false,
    vote_average: 6,
    vote_count: 1,
  },
  {
    backdrop_path: "/3Udwq6W7y4AIsuJDXV2YwowZ1gQ.jpg",
    id: 113962,
    name: "Lioness",
    original_name: "Lioness",
    overview:
      "Cruz Manuelos, a rough-around-the-edges but passionate young Marine, is recruited to join the CIA's Lioness Engagement Team to help bring down a terrorist organization from within. Joe, the station chief of the Lioness program, is tasked with training, managing and leading her female undercover operatives.",
    poster_path: "/ajaXSmdAlYYhnvx1EIsvpfN949y.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [18, 10768],
    popularity: 578.652,
    first_air_date: "2023-07-23",
    vote_average: 8,
    vote_count: 667,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/v6f9FUDDQfGIv8MLRQwlL0zvRjI.jpg",
    id: 203857,
    name: "The Diplomat",
    original_name: "The Diplomat",
    overview:
      "In the midst of an international crisis, a career diplomat lands in a high-profile job she’s unsuited for, with tectonic implications for her marriage and her political future.",
    poster_path: "/cOKXV0FalCYixNmZYCfHXgyQ0VX.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [18, 10768],
    popularity: 141.602,
    first_air_date: "2023-04-20",
    vote_average: 7.4,
    vote_count: 215,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/yLKkuYMcibmNEvb97I4t6eDSSwk.jpg",
    id: 1014214,
    title: "Singham Again",
    original_title: "सिंघम अगेन",
    overview:
      "The cop universe expands with newer additions while the old ones return led by Bajirao Singham. Singham Again interweaves the mythological epic Ramayana's good vs evil narrative when his wife Avni Kamath gets abducted by Danger Lanka setting Bajirao and his gang of Sangram Bhalerao and Veer Sooryavanshi along with Satya and Shakti Shetty on a mission to rescue her.",
    poster_path: "/2JbNkHg8m7LaBy61LyrnnlenaxY.jpg",
    media_type: "movie",
    adult: false,
    original_language: "hi",
    genre_ids: [28, 18],
    popularity: 105.539,
    release_date: "2024-11-01",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    backdrop_path: "/3V4kLQg0kSqPLctI5ziYWabAZYF.jpg",
    id: 912649,
    title: "Venom: The Last Dance",
    original_title: "Venom: The Last Dance",
    overview:
      "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
    poster_path: "/k42Owka8v91trK1qMYwCQCNwJKr.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [878, 28, 12],
    popularity: 5691.793,
    release_date: "2024-10-22",
    video: false,
    vote_average: 6.728,
    vote_count: 359,
  },
  {
    backdrop_path: "/xlkclSE4aq7r3JsFIJRgs21zUew.jpg",
    id: 1034541,
    title: "Terrifier 3",
    original_title: "Terrifier 3",
    overview:
      "Five years after surviving Art the Clown's Halloween massacre, Sienna and Jonathan are still struggling to rebuild their shattered lives. As the holiday season approaches, they try to embrace the Christmas spirit and leave the horrors of the past behind. But just when they think they're safe, Art returns, determined to turn their holiday cheer into a new nightmare. The festive season quickly unravels as Art unleashes his twisted brand of terror, proving that no holiday is safe.",
    poster_path: "/63xYQj1BwRFielxsBDXvHIJyXVm.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [27, 53],
    popularity: 4308.913,
    release_date: "2024-10-09",
    video: false,
    vote_average: 7.369,
    vote_count: 386,
  },
  {
    backdrop_path: "/xguH5MrPgl0nPSTEH9OBZ6ZieZA.jpg",
    id: 252372,
    name: "Murder Mindfully",
    original_name: "Achtsam Morden",
    overview:
      "When mafia lawyer Björn attends a mindfulness class to find a better work-life balance, he discovers surprising new coping strategies — including murder.",
    poster_path: "/3snsd7KLau14equwCz9YLZu9lTO.jpg",
    media_type: "tv",
    adult: false,
    original_language: "de",
    genre_ids: [35, 80],
    popularity: 97.005,
    first_air_date: "2024-10-31",
    vote_average: 8.3,
    vote_count: 3,
    origin_country: ["DE"],
  },
  {
    backdrop_path: "/bmovbAepfiKM3nGdsgFv54VGM2d.jpg",
    id: 1001083,
    title: "Meanwhile on Earth",
    original_title: "Pendant ce temps sur Terre",
    overview:
      "Elsa and Franck used to be close siblings, but everything changed when Franck’s space mission went awry. 3 years have passed since his mysterious disappearance, and 23-year-old Elsa is having trouble moving on with her life. One day, an unidentified life form contacts her, offering to bring her big brother back to Earth. But there is a price to pay…",
    poster_path: "/5SxwmxZnGNkTe8VBlXuVJnKH7JY.jpg",
    media_type: "movie",
    adult: false,
    original_language: "fr",
    genre_ids: [18, 878],
    popularity: 2.14,
    release_date: "2024-07-03",
    video: false,
    vote_average: 6.9,
    vote_count: 11,
  },
  {
    backdrop_path: "/bamB26mEh8Z0CR2nKK6TIGSDWNY.jpg",
    id: 256116,
    name: "Like a Dragon: Yakuza",
    original_name: "龍が如く～Beyond the Game～",
    overview:
      "Set in the fictional town of Kamurocho, the story unfolds across two intersecting timelines—1995 and 2005. In 1995, four friends eager to escape their restrictive lives in an orphanage dive into the yakuza-controlled underworld of 1995 Kamurocho. Meanwhile, in 2005, their friendship is deteriorated, as tensions between the Tojo Clan and the Omi Alliance are at a boiling point.",
    poster_path: "/4uFt0lyo2UrMkTKCXH2VgxWz2jE.jpg",
    media_type: "tv",
    adult: false,
    original_language: "ja",
    genre_ids: [10759, 80, 18],
    popularity: 131.48,
    first_air_date: "2024-10-25",
    vote_average: 6,
    vote_count: 9,
    origin_country: ["JP"],
  },
  {
    backdrop_path: "/kwXycPsLA6SV3KUOagn343TtMOf.jpg",
    id: 791042,
    title: "Levels",
    original_title: "Levels",
    overview:
      "After witnessing his girlfriend's murder, a man risks everything - including reality itself - to discover the truth.",
    poster_path: "/y1xm0jMIlx9Oo2a3jWNyLGm43sJ.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [28, 878, 53],
    popularity: 31.958,
    release_date: "2024-11-01",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    backdrop_path: "/1HsBOiOpu8okZ56OBdnWJ1lIX0I.jpg",
    id: 273081,
    name: "Don't Come Home",
    original_name: "อย่ากลับบ้าน",
    overview:
      "A mother must confront dark secrets from the past when her young daughter mysteriously vanishes after they move into her family’s eerie old mansion.",
    poster_path: "/mtIm0qbFnQ3oqqDrVpPTJDS6EZK.jpg",
    media_type: "tv",
    adult: false,
    original_language: "th",
    genre_ids: [9648],
    popularity: 64.551,
    first_air_date: "2024-10-31",
    vote_average: 10,
    vote_count: 1,
    origin_country: ["TH"],
  },
  {
    backdrop_path: "/lk2V8WFnAoXa44q8vqVeYyK6WJK.jpg",
    id: 1214484,
    title: "Let Go",
    original_title: "Släpp taget",
    overview:
      "A jaded mother makes a last-ditch effort to keep her family together by taking them on a trip to their teenage daughter’s pole dancing competition.",
    poster_path: "/hRuo0CXc5XINxVnMIA2r5fjzqVD.jpg",
    media_type: "movie",
    adult: false,
    original_language: "sv",
    genre_ids: [18],
    popularity: 25.903,
    release_date: "2024-11-01",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
];

function fetchData(setTrending) {
  fetch(url, options)
    .then((response) => response.json())
    .then((data) => {
      const results = data.results;
      console.log(results);
      return results;
    })
    .then(setTrending);
  fetched = true;
}

const url = "https://api.themoviedb.org/3/trending/all/day?language=en-US";
const options = {
  method: "GET",
  headers: {
    accept: "application/json",
    Authorization:
      "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI2Y2VkN2Y4Yzg3NjQ3NWQxMjE1NGUwZTcxYWI1YjY2MyIsIm5iZiI6MTczMDQ2MzI0MS45ODgwNjU3LCJzdWIiOiI2NzI0YmJjZWMxYzc0MzNlYmJjNDI5OTEiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.s_qvHsk_NAVv-3PXUeMfm_LT2sXOEy4A2slc4evjhPk",
  },
};

const configs = {
  images: {
    base_url: "http://image.tmdb.org/t/p/",
    secure_base_url: "https://image.tmdb.org/t/p/",
    backdrop_sizes: ["w300", "w780", "w1280", "original"],
    logo_sizes: ["w45", "w92", "w154", "w185", "w300", "w500", "original"],
    poster_sizes: ["w92", "w154", "w185", "w342", "w500", "w780", "original"],
    profile_sizes: ["w45", "w185", "h632", "original"],
    still_sizes: ["w92", "w185", "w300", "original"],
  },
  change_keys: [
    "adult",
    "air_date",
    "also_known_as",
    "alternative_titles",
    "biography",
    "birthday",
    "budget",
    "cast",
    "certifications",
    "character_names",
    "created_by",
    "crew",
    "deathday",
    "episode",
    "episode_number",
    "episode_run_time",
    "freebase_id",
    "freebase_mid",
    "general",
    "genres",
    "guest_stars",
    "homepage",
    "images",
    "imdb_id",
    "languages",
    "name",
    "network",
    "origin_country",
    "original_name",
    "original_title",
    "overview",
    "parts",
    "place_of_birth",
    "plot_keywords",
    "production_code",
    "production_companies",
    "production_countries",
    "releases",
    "revenue",
    "runtime",
    "season",
    "season_number",
    "season_regular",
    "spoken_languages",
    "status",
    "tagline",
    "title",
    "translations",
    "tvdb_id",
    "tvrage_id",
    "type",
    "video",
    "videos",
  ],
};
